name: Release Please

on:
  workflow_run:
    workflows:
      - "run-tests"
    types:
      - completed
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  # Wait for other workflows to complete successfully
  wait-for-checks:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_run'
    steps:
      - name: Check workflow run conclusion
        if: github.event.workflow_run.conclusion != 'success'
        run: |
          echo "Required workflow failed: ${{ github.event.workflow_run.name }}"
          exit 1

  release-please:
    runs-on: ubuntu-latest
    needs: [wait-for-checks]
    if: always() && (needs.wait-for-checks.result == 'success' || github.event_name == 'workflow_dispatch')
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: release-please-action
        uses: googleapis/release-please-action@v4.3.0
        id: release
        with:
          release-type: php
          config-file: .github/release-please-config.json
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.GITHUB_TOKEN }}
